name: ball
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  audioplayers: ^6.4.0

  cloud_firestore: ^5.6.8
  connectivity_plus: ^6.1.5
  custom_info_window: ^1.0.1
  dartz: ^0.10.1
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_hooks: ^0.21.2
  flutter_native_splash: ^2.4.6
  flutter_polyline_points: ^2.1.0
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.2.0
  geolocator: ^14.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  
  
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  maps_launcher: ^3.0.0+1
  path: ^1.9.0
  pausable_timer: ^3.1.0+3
  permission_handler: ^12.0.0+1
  persistent_bottom_nav_bar: ^6.2.1
  riverpod_annotation: ^2.3.5
  
  shared_preferences: ^2.3.2
  show_custom_snackbar: ^0.0.1
  smooth_page_indicator: ^1.2.1
  sqflite: ^2.4.2
  top_snackbar_flutter: ^3.3.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  drift_dev: ^2.20.3
  change_app_package_name: ^1.5.0


  
flutter:
  uses-material-design: true

  assets:
  - assets/audio/
  - assets/images/
  - assets/images/png/
  - assets/images/svg/
  - assets/basketball_courts_in_nigeria.json
