name: ball
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  drift_dev: ^2.20.3
  
flutter:
  uses-material-design: true
